---
title: "NBA Stat Test File"
output: html_document
date: "2023-02-15"
---

```{r setup, include=FALSE}
#####################
# Step 2: Install packages
#####################
# install.packages("wesanderson")
# install.packages("plyr")
# install.packages("tidyverse")
# install.packages("rvest")
# install.packages("ggrepel")
# install.packages("readr")
# install.packages("RCurl")
# install.packages("jpeg")

#####################
# Step 3: Load libraries
#####################
library(dplyr)
library(plyr)
library(tidyverse)
library(rvest)
library(ggrepel)
library(readr)
library(RCurl)
library(jpeg)
```

```{r cars}
#####################
## Step 4: Get player stats from bballref
#####################
# Add player name and player slug
player <- "Jason Kidd"
player_name_split <- tolower(strsplit(player, " ")[[1]])
slug_ln <- substr(player_name_split[2], start = 1, stop = 5)
slug_fn <- substr(player_name_split[1], start = 1, stop = 2)
slug <- paste0(slug_ln, slug_fn, '01')#"bryanko01" 
print(slug)

# define player page URL and player image URL
url <- paste0("https://www.basketball-reference.com/players/",substr(slug,1,1),"/",slug,".html")
image_url <- paste0("https://www.basketball-reference.com/req/202106291/images/players/",slug,".jpg")

print(image_url)
```

```{r pressure, echo=FALSE}
# Read total stats.
ttl_stat <- url %>%
  read_html %>%
  html_node("#totals") %>% 
  html_table()

# Read advanced stats.
adv_stat <- url %>%
  read_html %>%
  html_node("#advanced") %>% 
  html_table()

# Merge stats tables.
total_stats <- merge(ttl_stat, adv_stat, by=c("Season","Age", "Tm", "Lg", "Pos", "G", "MP"))

# View(player_stats)
```

```{r}
player_stats <- total_stats |> select(c('Season', 'Age', 'Tm', 'Pos', 'G', 'FG%', 'TRB', 'AST', 'STL', 'BLK', 'PTS'))

player_stats <- player_stats |>
  mutate('TRB per game' = round(player_stats$TRB / player_stats$G, 2),
         'AST per game' = round(player_stats$AST / player_stats$G, 2),
         'STL per game' = round(player_stats$STL / player_stats$G, 2),
         'BLK per game' = round(player_stats$BLK / player_stats$G, 2),
         'PTS per game' = round(player_stats$PTS / player_stats$G, 2))

player_exp_no_na <- player_stats |> filter(!is.na(player_stats$Age))
player_exp <- length(unique(player_exp_no_na$Age))

player_first_season <- min(unique(player_exp_no_na$Season))
player_last_season <- max(unique(player_exp_no_na$Season))

player_age <- max(player_exp_no_na$Age, na.rm = TRUE)

typeof(player_first_season)
print(player_last_season)
                                     
print(player_exp)
print(player_age)

typeof(player_exp)

```

```{r}
position_map <- function(pos) {
  pos <- toupper(pos)  # convert input to all uppercase
  switch(pos,
         "PG" = "Point Guard",
         "SG" = "Shooting Guard",
         "SF" = "Small Forward",
         "PF" = "Power Forward",
         "C" = "Center")
}

```

```{r}
player_position_ls <- unique(player_exp_no_na$Pos)

player_positions <- ''

for (i in seq_along(player_position_ls)) {
  player_positions <- paste0(player_positions, 
                             position_map(player_position_ls[i]), 
                             collapse = "")
  if (i != length(player_position_ls)) {
    player_positions <- paste0(player_positions, ' & ', collapse = "")
  }
}

print(player_positions)

```

```{r}
# Define a function to map NBA team codes to team names
nba_teams_map <- function(team_code) {
  teams <- list(ATL = "Atlanta Hawks",
                BKN = "Brooklyn Nets",
                BOS = "Boston Celtics",
                CHA = "Charlotte Hornets",
                CHI = "Chicago Bulls",
                CLE = "Cleveland Cavaliers",
                DAL = "Dallas Mavericks",
                DEN = "Denver Nuggets",
                DET = "Detroit Pistons",
                GSW = "Golden State Warriors",
                HOU = "Houston Rockets",
                IND = "Indiana Pacers",
                LAC = "Los Angeles Clippers",
                LAL = "Los Angeles Lakers",
                MEM = "Memphis Grizzlies",
                MIA = "Miami Heat",
                MIL = "Milwaukee Bucks",
                MIN = "Minnesota Timberwolves",
                NOP = "New Orleans Pelicans",
                NJN = "Brooklyn Nets",
                NYK = "New York Knicks",
                OKC = "Oklahoma City Thunder",
                ORL = "Orlando Magic",
                PHI = "Philadelphia 76ers",
                PHO = "Phoenix Suns",
                PHX = "Phoenix Suns",
                POR = "Portland Trail Blazers",
                SAC = "Sacramento Kings",
                SAS = "San Antonio Spurs",
                TOR = "Toronto Raptors",
                TOT = "Two Other Teams",
                UTA = "Utah Jazz",
                WAS = "Washington Wizards")
  return(teams[[team_code]])
}

```

```{r}
player_team_ls <- unique(player_exp_no_na$Tm)

player_teams <- c()

for (team in player_team_ls) {
  player_teams <- c(player_teams, nba_teams_map(team))
}

print(player_teams)
```
